services:
  bgpmonitor-dump:
    container_name: peering_bgpmonitor
    build: ./bgpdownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
      - /etc/peering/monitor/config.json:/usr/source/app/config.json
  ripemonitor-dump:
    container_name: peering_ripemonitor
    build: ./ripedownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
      - /etc/peering/monitor/config.json:/usr/source/app/config.json
    cap_drop:
      - SYS_ADMIN
      - SETUID
      - SETGID
      - CHOWN
      - FOWNER

  peeringrov-dataprocessing:
    container_name: peering_dataprocessing
    build: ./dataprocessing
    volumes:
      - /etc/peering/monitor/data/:/var/monitor/data
      - /etc/peering/monitor/config.json:/usr/source/app/config.json
