services:
  bgpmonitor-dump:
    container_name: peering_bgpmonitor
    build: ./bgpdownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
      - /etc/peering/monitor/config.json:/root/config.json
  ripemonitor-dump:
    container_name: peering_ripemonitor
    build: ./ripedownloader
    volumes:
      - /etc/peering/monitor/data:/var/monitor/data
      - /etc/peering/monitor/config.json:/root/config.json
  peeringrov-dataprocessing:
    container_name: peering_dataprocessing
    build: ./dataprocessing
    volumes:
      - /etc/peering/monitor/data/:/var/monitor/data
      - /etc/peering/monitor/config.json:/root/config.json
